language: cpp
dist: trusty
sudo: required
compiler:
- clang
os:
- linux
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update
- sudo apt-get install -y libc++-dev libc++abi-dev bsdtar libedit-dev
- mkdir -p build/bin
- export PATH=`pwd`/build/bin:$PATH
before_script:
- curl -O $RELEASE_URL/$RUBINIUS_TAR
- tar -xjf $RUBINIUS_TAR
- cd $RUBINIUS_DIR
script:
- "./configure"
- "./scripts/deploy.sh heroku"
branches:
  only:
  - heroku
  - homebrew
  - travis-osx
  - travis-14.04
notifications:
  email: false
  webhooks:
    urls:
      secure: cDhSNzRRBr3n5IpNVk/evO7u/N2Jo6LOsBfmYTJmuhfb95m9vbeM+IuA6rBM9RyF5njckheLNrytr9rq2aLidVOkOxx9n+4KpDlP1zb3xF7BBgFzYT8DJcwzxrDgkv0bghrs8RCQBV1ykD+iVv4P+tAEOCu5IPQa7+jcgGwdjUVf8uOE6q86zKNf2g9SmvGUAyDKg2vik/BGEYqqDsiGlGG0qqI6T4ggLWd889u4Af/eYkNq7uldcrb/QSUNoIUz2eRf+2hmyknd31fS0/mLIhENdDZEaLAgmsVeVl09Rla8f0OUvX0p34PXRVPeinqbqr7EEKlGMhPzi3wNaXgP5gn6iaWLHZ9JsAqrv/7zAINJsvVWfMH0iI77VPYbWYzaDT4KhJvUuXx9sqL+KFCg9YVlCNbLc+TXLaniJsIpAti/fesY26DzqlD1dxiMljJrk181T2nhOQLFzanfLl1oq23/ukwiVSmg0+ZL9+0usHwdffoWw6JlLkgmyqcV5Ktfe3QZ3fc2/6vez6ECC1VoKR4bcwCgcq6q8EOvh0yLCV+UcuRSxcBqQUn0QJU9OxcbTU8NkLlaXvydZyZd0B94Xq4n6pfWQe4m6wq2wnDRlpiBJR5okFg0VxNKgfnF+oEA1erMjvPEg2U+JlV9mUcw4rqnfihXI1zEelnGJBKC6vE=
    on_success: change
    on_failure: always
    on_start: always
env:
  global:
  - RELEASE_URL=https://rubinius-releases-rubinius-com.s3.amazonaws.com
  - RUBINIUS_VERSION=3.106
  - RUBINIUS_DIR=rubinius-$RUBINIUS_VERSION
  - RUBINIUS_TAR=rubinius-$RUBINIUS_VERSION.tar.bz2
  - LANG="en_US.UTF-8"
  - secure: psuqNqOzR6A4owyO4KGKLazbuYCvQzOM5c9mx+VHySvdFBCxlxTkubkJKahxN2iy9YAvGN1uF3aeKvvqMIwnMZnmLhnsqASMfXQcVHi5sAwVs2vr5/Ve9XNE7cE60TcvWPCmSsolI6l4bnlu7y1hnTUod2VeAXFsvE0acPE3n9WcohbqMcC2MaesGFpzhc39brhVOVs5XsMBKsHzUx7U6pdBy7RmiSoJm8RGQ8piAYP714uwU2+K6J6Joeg+plnNUEi6PqR8e9R4JMy6eSsvjtJ/FX6W5GRbT1bj3DnCGt6SfU5W+99xKv9IW2vbfdszgyqPaMRP4S/E6b+9hhO0qQ36aRKAVNM7EF5BFR0R0GoRzwR622USKGBonUGSvD+bcqIL40Nmvx0gzTotke0J0dkdCCYdGVUPM8c2igkvxgZmpPzxtfcF3TUHJ9a47tPDG6dQPXQB/Xd09pw0cHl4xdIwGJxTqRZI9ze9uJU+iYaFersbzft0PxL+xL3F6ZrYHrBITAQTbS1m0hCMJE9NTpbCQ9FXQXEaz+e3bHyCnMVfR3pk5T3GWegP701l317vHRus9covdwQYCL/RM7MIjwNfLD3CYCfP/xB3hsbldMU6yqpPyMZlYBfGhAKj84ZJ5zZPCDPQtVxeTEaTE//enrkyA+Xx0t/bh0rARo5DLig=
  - secure: KIIifAckcbIJ/i2Td2qnDcdDolYLde1osGN+05NWcOCPR3g2uo3HNAllhOMOsxcp81mprX3IIvuKFMX12DO3B6Le+S5/K/IDsebLb1Q68oqLWckC81Xz2eQd+WLTmRImHNo/yZarBEkrthbRVAYMtlcnw01GnYZ6ydrtVKB8kgI/FiKG98sA6C0CwEg2jJ+k1gqf5iw4uJp7Z4kQ7evtDrigc2U/XxcxaGqAVLWLA916YNOAd6U1CYOiFzobvNTkt6ZiImvacrMLwD8OQFlyxTnCSDamqcJ+kGN0t8dXZmUlT/4L992H16tMjvJm+0MLdx1qef95QKzlIT4CnlkbQKEQuWNVGmeiiJL+4HH0Ak3Bc88co/QyLssGF8OJlMbr9Ht4cjsY89/9REfZUHWa8wCdyoPdkqv49qNBVVC/VLoWBwAN/wO4iIHB90j/BG5FLb/ATL1kuRnl8u2un6RBmcbFE8jxRiozbcy6zmqYIupDsowtq/oe4c2ZdAgcPAkb8EAOt0qJn8PGSPPOxyydAguepJtltqv2T9Xwtnac2j7rTW1oFbTtqVUrO/Wp+7wbV0Z28S3dO0KJqz2KkXnoAn50kSSDPaIVbYEih8ko005GAuUW3wN6J9MJgacRs3bmwHlFDxqd0DziG6Sk7TlMLa8lIzAQHL1cc4O3WGoWokw=
  - secure: cmecpiyKtC0+RXBLo2yOkEFVEQ2eRY29i35WcI9E2wHYFVS+IwE61FXv+jJjkArRz5N8cYIxH4Kn5CR35oprYnd4aWCTp6kEladwRB1hDqsBkKDZFqUPa8kdVDyhaIn0oWVj+L6u/bP9UPaflJTkNRLtUc4gZlTnbdkOtUcjsYqIhRberZ1RFd9uEeju4fvKn6u7ykspgPHBLuMwC7bYC+ucOZUWcdo6SfHwjO8eaHfeXYT/xE/5MKXbvp9852NdCqjKFf0gnNi5sHow9WiZLeE4L8c+yWBBlPvIJNyKIhTtrtwAz8oCByTw5n8H8W/ZXvCzrT8pC695ULzEtrHZAUUgcoPYveQQCQHhRJIDnITwxlXaqCPIK96c0kYcGx6SItC8mMv+jMlyD1rkKw7MHYSwPx2uBk59M+06GLm9ChvdFMuIRcxrqKv/rl+Pz0EOHgVZtw3IT+969hfIPd3ukJNrdvmavf0H3gL1BfZvl41jjzm/RH77315qyY+q7Ld7zUysHuoRu4vJJYHQ37tM5Ho3xfuha5GIA5Pw/VKY0p/u/pOXWL7DoBW4LQebBPCAYW6zbXZah3rxoDHgC/jMrMGLwO+Hw82r81fE80ZZ1+TcKqwtD54WEVtyUw7NJ0y0pYYYclA9xRQAiBhxDkqQ9Zua3rToD9Xy4OmMyqnpvmA=
