language: cpp
sudo: required
compiler:
- clang
os:
- linux
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update
- sudo apt-get install -y clang-3.6 llvm-3.6-dev libedit-dev
before_script:
- curl -O $RELEASE_URL/$RUBINIUS_TAR
- tar -xjf $RUBINIUS_TAR
- cd $RUBINIUS_DIR
script:
- "./configure"
- "./scripts/deploy.sh travis docker"
branches:
  only:
  - heroku
  - homebrew
  - travis-osx
  - travis-12.04
  - travis-14.04
notifications:
  email: false
  webhooks:
    urls:
      secure: liv06jAh0pL96BUFq+ZJes8jWAGpsbOBVCPOqvFEpeSUj9+PLu1kDPEPTpiUNuGyekXfZLZkS/Asss1Dzpmv96uOsHDcloT8FkFAvnd5tOdblyH72hf1U1h6Fyy32Grbcy4icwkKLRyriYRwbWIUqFskoxbhj6RG4JMmcTsiULC7K97dB3bwLiJ2UtYkX8v+G8jKoOfkEv7eZwf3pDjDMu1Fcy7vrTqwmkQ28iXOfb2JXkfGEKwZs39J/+Trz6n1Yd4wIedep1viCNp4bKj7iwj27Vtdv28LtSDUcO02N7QZDY01upbJItSiiRs9MKCIN7JUmB4/i44A7CgivE1pTAJgk/Lb4emyljciWULzWjr1KE9F2pYpjue5Y1AwV980ihUvUP4zutc30shsIrAPMcMzJBJtRRwCtHayWnoPOBalwz4efW4++krDpU7lEdK13hR228qxoXCrQRX596qKPUpi9pf1voXw//uQ8ctVNEDuYUtIjzK8h8vO0KsKtrFY9sj2DjHE1ILedg7ybAeHbNmIQ2bEdvlpiGJt75jgL7zaGcq5jNFktwFyr4Bxhz6Ljm4vd+oAdVU/Vl2OLIjAg36hq4yc1SMAoc4GsOzqY8RV6FZd9HzYtfsISAURwe4PwU7SMHLfHLHydL1S4iuP7GIK4H+PgSk+bXm24zH7m2U=
    on_success: change
    on_failure: always
    on_start: always
env:
  global:
  - RELEASE_URL=https://rubinius-releases-rubinius-com.s3.amazonaws.com
  - RUBINIUS_VERSION=3.16
  - RUBINIUS_DIR=rubinius-$RUBINIUS_VERSION
  - RUBINIUS_TAR=rubinius-$RUBINIUS_VERSION.tar.bz2
  - LANG="en_US.UTF-8"
  - secure: psuqNqOzR6A4owyO4KGKLazbuYCvQzOM5c9mx+VHySvdFBCxlxTkubkJKahxN2iy9YAvGN1uF3aeKvvqMIwnMZnmLhnsqASMfXQcVHi5sAwVs2vr5/Ve9XNE7cE60TcvWPCmSsolI6l4bnlu7y1hnTUod2VeAXFsvE0acPE3n9WcohbqMcC2MaesGFpzhc39brhVOVs5XsMBKsHzUx7U6pdBy7RmiSoJm8RGQ8piAYP714uwU2+K6J6Joeg+plnNUEi6PqR8e9R4JMy6eSsvjtJ/FX6W5GRbT1bj3DnCGt6SfU5W+99xKv9IW2vbfdszgyqPaMRP4S/E6b+9hhO0qQ36aRKAVNM7EF5BFR0R0GoRzwR622USKGBonUGSvD+bcqIL40Nmvx0gzTotke0J0dkdCCYdGVUPM8c2igkvxgZmpPzxtfcF3TUHJ9a47tPDG6dQPXQB/Xd09pw0cHl4xdIwGJxTqRZI9ze9uJU+iYaFersbzft0PxL+xL3F6ZrYHrBITAQTbS1m0hCMJE9NTpbCQ9FXQXEaz+e3bHyCnMVfR3pk5T3GWegP701l317vHRus9covdwQYCL/RM7MIjwNfLD3CYCfP/xB3hsbldMU6yqpPyMZlYBfGhAKj84ZJ5zZPCDPQtVxeTEaTE//enrkyA+Xx0t/bh0rARo5DLig=
  - secure: KIIifAckcbIJ/i2Td2qnDcdDolYLde1osGN+05NWcOCPR3g2uo3HNAllhOMOsxcp81mprX3IIvuKFMX12DO3B6Le+S5/K/IDsebLb1Q68oqLWckC81Xz2eQd+WLTmRImHNo/yZarBEkrthbRVAYMtlcnw01GnYZ6ydrtVKB8kgI/FiKG98sA6C0CwEg2jJ+k1gqf5iw4uJp7Z4kQ7evtDrigc2U/XxcxaGqAVLWLA916YNOAd6U1CYOiFzobvNTkt6ZiImvacrMLwD8OQFlyxTnCSDamqcJ+kGN0t8dXZmUlT/4L992H16tMjvJm+0MLdx1qef95QKzlIT4CnlkbQKEQuWNVGmeiiJL+4HH0Ak3Bc88co/QyLssGF8OJlMbr9Ht4cjsY89/9REfZUHWa8wCdyoPdkqv49qNBVVC/VLoWBwAN/wO4iIHB90j/BG5FLb/ATL1kuRnl8u2un6RBmcbFE8jxRiozbcy6zmqYIupDsowtq/oe4c2ZdAgcPAkb8EAOt0qJn8PGSPPOxyydAguepJtltqv2T9Xwtnac2j7rTW1oFbTtqVUrO/Wp+7wbV0Z28S3dO0KJqz2KkXnoAn50kSSDPaIVbYEih8ko005GAuUW3wN6J9MJgacRs3bmwHlFDxqd0DziG6Sk7TlMLa8lIzAQHL1cc4O3WGoWokw=
  - secure: lqALD01eTp+HlWKNtqUCBPeUFm9slDV4ytX8obQsWi3RmORCgi/uJO6f1Naoin96dM4tBMRZVYrYtk2ryBbgKwQQMad665JUmdEzVEj/eYJ5rL2wX33d7F6DA+68q7XMjMBWUSdQsmzBuf/qCLViP/zWWhalAUjF7WVbFvpohlfvAc3uWn83oJNCv2cQayVi/YIs+y4TobCyI3k0qNDoHWZwOCovJxbXLioiYfUazkwPg7t9KS9y0miZfiQM3HplTRCKsfTxa460GgC8f6DVX7y5baVJniT86/P3V2IuU8FXBspLUcZStKU0C0KVbtZSGoxiaeXvvCUT7cq2tnUBULftwgI0GKZz6zO6gPglWWV+Mr/PGHPAhwagY7G1ENOh+TUfuoxFxeJhdHIAJDr/R2CxMJy5T3k8PyKfD+cgwMXZTgKrV+Wuu0clQK+5CfNdgrhYgyrXrhlGo+8jk68KtqI+M3iwtGpF5pJc86V53eH3G/zchhxXCxacwalvVI3AVxMtbIctX6KBABZeqldxdq6potlb5o5aAc5/YGrdRohnds6qG04mqdWzm/nteJ4Xi7DQdouaOg5xd3KM/OcfHmq6U4WNimpeeFMSlRfcXuv2irSYe7gILrIPtCLtjD8vRkzRJJL4w/3npUtYq2UCjQdBR9VX7k3nrvqXjgJF4q4=
