language: cpp
sudo: required
compiler:
- clang
os:
- osx
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- brew update
- brew install llvm35
- brew link --force llvm35
before_script:
- curl -O $RELEASE_URL/$RUBINIUS_TAR
- tar -xjf $RUBINIUS_TAR
- cd $RUBINIUS_DIR
script:
- bundle
- ./configure
- ./scripts/deploy.sh homebrew
branches:
  only:
  - homebrew
  - travis-osx
  - travis-12.04
  - travis-14.04
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/9502afd22ca6c8e85fb3
    on_success: change
    on_failure: always
    on_start: always
env:
  global:
  - RELEASE_URL=https://rubinius-releases-rubinius-com.s3.amazonaws.com
  - RUBINIUS_VERSION=3.17
  - RUBINIUS_DIR=rubinius-$RUBINIUS_VERSION
  - RUBINIUS_TAR=rubinius-$RUBINIUS_VERSION.tar.bz2
  - LANG="en_US.UTF-8"
  - secure: psuqNqOzR6A4owyO4KGKLazbuYCvQzOM5c9mx+VHySvdFBCxlxTkubkJKahxN2iy9YAvGN1uF3aeKvvqMIwnMZnmLhnsqASMfXQcVHi5sAwVs2vr5/Ve9XNE7cE60TcvWPCmSsolI6l4bnlu7y1hnTUod2VeAXFsvE0acPE3n9WcohbqMcC2MaesGFpzhc39brhVOVs5XsMBKsHzUx7U6pdBy7RmiSoJm8RGQ8piAYP714uwU2+K6J6Joeg+plnNUEi6PqR8e9R4JMy6eSsvjtJ/FX6W5GRbT1bj3DnCGt6SfU5W+99xKv9IW2vbfdszgyqPaMRP4S/E6b+9hhO0qQ36aRKAVNM7EF5BFR0R0GoRzwR622USKGBonUGSvD+bcqIL40Nmvx0gzTotke0J0dkdCCYdGVUPM8c2igkvxgZmpPzxtfcF3TUHJ9a47tPDG6dQPXQB/Xd09pw0cHl4xdIwGJxTqRZI9ze9uJU+iYaFersbzft0PxL+xL3F6ZrYHrBITAQTbS1m0hCMJE9NTpbCQ9FXQXEaz+e3bHyCnMVfR3pk5T3GWegP701l317vHRus9covdwQYCL/RM7MIjwNfLD3CYCfP/xB3hsbldMU6yqpPyMZlYBfGhAKj84ZJ5zZPCDPQtVxeTEaTE//enrkyA+Xx0t/bh0rARo5DLig=
  - secure: KIIifAckcbIJ/i2Td2qnDcdDolYLde1osGN+05NWcOCPR3g2uo3HNAllhOMOsxcp81mprX3IIvuKFMX12DO3B6Le+S5/K/IDsebLb1Q68oqLWckC81Xz2eQd+WLTmRImHNo/yZarBEkrthbRVAYMtlcnw01GnYZ6ydrtVKB8kgI/FiKG98sA6C0CwEg2jJ+k1gqf5iw4uJp7Z4kQ7evtDrigc2U/XxcxaGqAVLWLA916YNOAd6U1CYOiFzobvNTkt6ZiImvacrMLwD8OQFlyxTnCSDamqcJ+kGN0t8dXZmUlT/4L992H16tMjvJm+0MLdx1qef95QKzlIT4CnlkbQKEQuWNVGmeiiJL+4HH0Ak3Bc88co/QyLssGF8OJlMbr9Ht4cjsY89/9REfZUHWa8wCdyoPdkqv49qNBVVC/VLoWBwAN/wO4iIHB90j/BG5FLb/ATL1kuRnl8u2un6RBmcbFE8jxRiozbcy6zmqYIupDsowtq/oe4c2ZdAgcPAkb8EAOt0qJn8PGSPPOxyydAguepJtltqv2T9Xwtnac2j7rTW1oFbTtqVUrO/Wp+7wbV0Z28S3dO0KJqz2KkXnoAn50kSSDPaIVbYEih8ko005GAuUW3wN6J9MJgacRs3bmwHlFDxqd0DziG6Sk7TlMLa8lIzAQHL1cc4O3WGoWokw=
  - secure: nkE0cyUYG1o3Nl47rRiCahyrJOkxwsilgcbqqejfLt80uqkGsBV8z7rjw+Cqe05eHeM9f3+5McW16jk95KDYiQPoeFPPcYKg7mkt79OE78r/apl3xjRe6r8dIoO7vs4C1Fj6EJZjNroI2PBu7xMm7P3SNE+/nGFCsjvhPhy6J6LlFvH6AbW9G04hCPhMxHH2C5uRhfvFOnj6AoYs9ZFhgsqWO6iE8fWliCk+QpoMt4TZNoMsRJy+2GJXwC6+a+JxquWo+wRloAmFzQSAhEzxtzquE/NIOC2elo7DonEbU5MCvocfmofO15R7Ng5xnh3yyvsat1E62ZpMUhwiZAc25NN/bTUPEZccl+DGmfKaJBaxoE2EXdhRbM87U3XwAWOc2p9/729gzN9hp1V+4g7JI+aAe3ws9H3i8juQebE/wNIhKAmcLGEsbUMBWQUOAG7KgzApBK7dsKo5iPRRla1kjApkIUSiqgAFsCtH/qyCbUzInCSpoTMFkeLMmZSKbKIL3Q5cuMPapK3UTQKp3J+in4mpQOK0csTE5+NtbZ+iN+8OmG04xf1jFKKkqH1IA49T7MIHc+kMDVajMosPqYnSKskToMAA9zO/2bWs7r3/sAWTgJOatB8Avtwtbvb5X74loO5b3yhWGL5Ap6/fegmINe0huub9x2cSqhKlo2Rjwe8=
