language: cpp
sudo: required
compiler:
- clang
os:
- osx
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- brew update
- brew install llvm
before_script:
- curl -O $RELEASE_URL/$RUBINIUS_TAR
- tar -xjf $RUBINIUS_TAR
- cd $RUBINIUS_DIR
script:
- "./configure --with-include-dir=$OPENSSL_DIR/include --with-lib-dir=$OPENSSL_DIR/lib"
- "./scripts/deploy.sh homebrew"
branches:
  only:
  - homebrew
  - travis-osx
  - travis-14.04
notifications:
  email: false
  webhooks:
    urls:
      secure: g+p3B/AlSunxyHQ4+B0hyD20OYNvwf8yy00QnImbD33Nf5a1zm/ID7x0QlDnFaXg1DjNxINgHRirG9g1nm/CfBnUhHADeHlheQov0GNoXuCyIDuHk/3P1jLfDUvCPQkRmsG+QwGLmazLJ28yD1D90YDCyIe+Wxgv1j53LjEkBQCcoo3Axc9HF/pJG4aT4Q9ofz0ySuM1K3iFUX69Uo3dw28pX6OiuOF1ahQuvyYZWJSr3RBOzG6HrOQgdKHbonUX5DheEYXznRW3DPeqtXFriu56Xmwbb4ripelQ9PEEXWjbTeD9sz0gk01lzdcUx/2Q/PK7H7z467gnyWDxEipHIMFLseM95Iv9EjVLMJdCKdqaTxZRq8LZ8CvyU+Z/H/pVHoGrY5FepOuGZNdURMabLadpoaCrJcLa2PHYAaysQLjjqO/lutp4h5CImzDK7eWLjH67J2WI9KN3rlevEwJoXBCGRep2r5myCzfsZFdh2aberGjQK0Tbacs6sKFdVR4CLjuLFEDIdtxn8RT9aTaaJ3sHeM+LuXqCuaUI1XDX21rMQybuzW1Vli5/0ob1Om4FpjfiswEjXq/J+C8gz21ryUTvu1uWiXKlMakAudclmobRmd/2PsFlBYxmfF7zdDlrbwSDvqpyKtHDGGylD94QLWgQeQW/U6+h0dbSF1vyBdA=
    on_success: change
    on_failure: always
    on_start: always
env:
  global:
  - RELEASE_URL=https://rubinius-releases-rubinius-com.s3.amazonaws.com
  - RUBINIUS_VERSION=3.100
  - RUBINIUS_DIR=rubinius-$RUBINIUS_VERSION
  - RUBINIUS_TAR=rubinius-$RUBINIUS_VERSION.tar.bz2
  - OPENSSL_DIR=$(brew --prefix openssl)
  - LANG="en_US.UTF-8"
  - secure: psuqNqOzR6A4owyO4KGKLazbuYCvQzOM5c9mx+VHySvdFBCxlxTkubkJKahxN2iy9YAvGN1uF3aeKvvqMIwnMZnmLhnsqASMfXQcVHi5sAwVs2vr5/Ve9XNE7cE60TcvWPCmSsolI6l4bnlu7y1hnTUod2VeAXFsvE0acPE3n9WcohbqMcC2MaesGFpzhc39brhVOVs5XsMBKsHzUx7U6pdBy7RmiSoJm8RGQ8piAYP714uwU2+K6J6Joeg+plnNUEi6PqR8e9R4JMy6eSsvjtJ/FX6W5GRbT1bj3DnCGt6SfU5W+99xKv9IW2vbfdszgyqPaMRP4S/E6b+9hhO0qQ36aRKAVNM7EF5BFR0R0GoRzwR622USKGBonUGSvD+bcqIL40Nmvx0gzTotke0J0dkdCCYdGVUPM8c2igkvxgZmpPzxtfcF3TUHJ9a47tPDG6dQPXQB/Xd09pw0cHl4xdIwGJxTqRZI9ze9uJU+iYaFersbzft0PxL+xL3F6ZrYHrBITAQTbS1m0hCMJE9NTpbCQ9FXQXEaz+e3bHyCnMVfR3pk5T3GWegP701l317vHRus9covdwQYCL/RM7MIjwNfLD3CYCfP/xB3hsbldMU6yqpPyMZlYBfGhAKj84ZJ5zZPCDPQtVxeTEaTE//enrkyA+Xx0t/bh0rARo5DLig=
  - secure: KIIifAckcbIJ/i2Td2qnDcdDolYLde1osGN+05NWcOCPR3g2uo3HNAllhOMOsxcp81mprX3IIvuKFMX12DO3B6Le+S5/K/IDsebLb1Q68oqLWckC81Xz2eQd+WLTmRImHNo/yZarBEkrthbRVAYMtlcnw01GnYZ6ydrtVKB8kgI/FiKG98sA6C0CwEg2jJ+k1gqf5iw4uJp7Z4kQ7evtDrigc2U/XxcxaGqAVLWLA916YNOAd6U1CYOiFzobvNTkt6ZiImvacrMLwD8OQFlyxTnCSDamqcJ+kGN0t8dXZmUlT/4L992H16tMjvJm+0MLdx1qef95QKzlIT4CnlkbQKEQuWNVGmeiiJL+4HH0Ak3Bc88co/QyLssGF8OJlMbr9Ht4cjsY89/9REfZUHWa8wCdyoPdkqv49qNBVVC/VLoWBwAN/wO4iIHB90j/BG5FLb/ATL1kuRnl8u2un6RBmcbFE8jxRiozbcy6zmqYIupDsowtq/oe4c2ZdAgcPAkb8EAOt0qJn8PGSPPOxyydAguepJtltqv2T9Xwtnac2j7rTW1oFbTtqVUrO/Wp+7wbV0Z28S3dO0KJqz2KkXnoAn50kSSDPaIVbYEih8ko005GAuUW3wN6J9MJgacRs3bmwHlFDxqd0DziG6Sk7TlMLa8lIzAQHL1cc4O3WGoWokw=
  - secure: Y6blay06ZxB+6BjW1j276UxOQoQaZJXMRZl74dqdH3BdNc+SBZ47wjH161PJb3Ja/to2e9NnzNoc7SKMY7ugWBtd3ZBNeNxti7qqTAP/job6A/NSdE1+bMVLwITZgVwiL6+nIGXMCwT64+/H7UVcc3rTDROukHd2C0VypwSTdLAhuBDyuyoH6pekA4R1lM33wn059eVdjptCCCP3UNC8k8AhbFr75tf7sAa3rS7nn8KMi5ZA6PCWhIHIYY2YspHzyntys1G853U+aY1W+dhE1OK/BOZ2N6knq/SVbo5zNtlC+z2uB+VEl4oGl5JfEsyjmkJwzdkdSiknuBExTV795nTbTs0jmlgJkgTK6oE0tz+1iN3SUQTbUbDif040R/QWN7dHo7IyF80yMQiW8WxH11SEePT4upXo5gmIPDfrN+y1DHd5RSfoXQ3GVL3Db0byHujueKV2EKp8ogz55eFRhNKkagv9nQHwP2AUY9WnXrKfhmLOZsEYtWjQb5KyQ2epL6cYyIjCxSyz7HhkfmJLUQ9OSir0xzZPvHuW4bfThzbCAlZedZfJWfwtUx16eSoFyEB3EnGmijl3AsKpT2FQSEuMO7NA1tnZmDp3vM5tjE0u1Bobk7IvuFSMGwga5GbQzGrA5jMnKGGSBXkP9Bof9ioqPEwi5k0FW9hpfK9RYbI=
