language: cpp
dist: xenial
sudo: required
compiler:
- clang
os:
- linux
ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- sudo apt-get update
- sudo apt-get install -y bsdtar libedit-dev
- mkdir -p build/bin
- export PATH=`pwd`/build/bin:$PATH
before_script:
- curl -O $RELEASE_URL/$RUBINIUS_TAR
- tar -xjf $RUBINIUS_TAR
- cd $RUBINIUS_DIR
script:
- "./configure"
- "./scripts/deploy.sh travis docker"
branches:
  only:
  - heroku
  - homebrew
  - travis-osx
  - travis-14.04
  - travis-16.04
notifications:
  email: false
  webhooks:
    urls:
      secure: XbDMcD0UA03C/KtACO733FSfn0uTO7IZcwsi6dU5KVVFORJ6ch7mFJP9TwWiSYRsgL2Q6ok9YgMbzJkbFTpOjn5QfaMKUudtov5KSBXPeW20ZHShYm57K9IT8DxGqwFYFjJCmimcjr7XuOiT1Vjw4q/ErmWaJIpT8CFr902c26EkdAiM869sz0nap9L6ymNcnf/W90P9/9L7M5ffDSDrly8f0mx81Nh8vKfBYGweR0h8445CsifF1x78CAYztYZVKA040T3rhHIieZ2ADXgntecdfjlsliHT/kEb5cAuEoBDSCdfcwzHuksHVV/qifVauazYaeDzuF7a+eLqyAvE1/FlX3CanSzACX7/hDGWXGrZ0lio3eOHjM70xsPjNCwuYpXyoGbZqMYFPGF1TLK7K3IuyBnW2zkI8bpG14llCSBuoDhEZBBrHGtXLYhaDOrTIEE5zKIyhyWI+Ewhq0gCsoR7siVl2SO4p1EaMJeLxI46lM0NOGeppLKrTm6KYPWjC+yG3oF+HqgEEXJt8WSWy4hNOq181+gR2MaYqvPI0oB0y3yxfgw+zlbUuGOoBZtZYu66/xaoacidwUGBmqjyfvv3EImXSyt9kX291xNvqU/LvyBEQ5a+ISx/JGqf5hiILGfyH8MRXmJVAb4UqbnTFhKG/FAkyI1hWef/a0/kSE4=
    on_success: change
    on_failure: always
    on_start: always
env:
  global:
  - RELEASE_URL=https://rubinius-releases-rubinius-com.s3.amazonaws.com
  - RUBINIUS_VERSION=4.11
  - RUBINIUS_DIR=rubinius-$RUBINIUS_VERSION
  - RUBINIUS_TAR=rubinius-$RUBINIUS_VERSION.tar.bz2
  - LANG="en_US.UTF-8"
  - secure: psuqNqOzR6A4owyO4KGKLazbuYCvQzOM5c9mx+VHySvdFBCxlxTkubkJKahxN2iy9YAvGN1uF3aeKvvqMIwnMZnmLhnsqASMfXQcVHi5sAwVs2vr5/Ve9XNE7cE60TcvWPCmSsolI6l4bnlu7y1hnTUod2VeAXFsvE0acPE3n9WcohbqMcC2MaesGFpzhc39brhVOVs5XsMBKsHzUx7U6pdBy7RmiSoJm8RGQ8piAYP714uwU2+K6J6Joeg+plnNUEi6PqR8e9R4JMy6eSsvjtJ/FX6W5GRbT1bj3DnCGt6SfU5W+99xKv9IW2vbfdszgyqPaMRP4S/E6b+9hhO0qQ36aRKAVNM7EF5BFR0R0GoRzwR622USKGBonUGSvD+bcqIL40Nmvx0gzTotke0J0dkdCCYdGVUPM8c2igkvxgZmpPzxtfcF3TUHJ9a47tPDG6dQPXQB/Xd09pw0cHl4xdIwGJxTqRZI9ze9uJU+iYaFersbzft0PxL+xL3F6ZrYHrBITAQTbS1m0hCMJE9NTpbCQ9FXQXEaz+e3bHyCnMVfR3pk5T3GWegP701l317vHRus9covdwQYCL/RM7MIjwNfLD3CYCfP/xB3hsbldMU6yqpPyMZlYBfGhAKj84ZJ5zZPCDPQtVxeTEaTE//enrkyA+Xx0t/bh0rARo5DLig=
  - secure: KIIifAckcbIJ/i2Td2qnDcdDolYLde1osGN+05NWcOCPR3g2uo3HNAllhOMOsxcp81mprX3IIvuKFMX12DO3B6Le+S5/K/IDsebLb1Q68oqLWckC81Xz2eQd+WLTmRImHNo/yZarBEkrthbRVAYMtlcnw01GnYZ6ydrtVKB8kgI/FiKG98sA6C0CwEg2jJ+k1gqf5iw4uJp7Z4kQ7evtDrigc2U/XxcxaGqAVLWLA916YNOAd6U1CYOiFzobvNTkt6ZiImvacrMLwD8OQFlyxTnCSDamqcJ+kGN0t8dXZmUlT/4L992H16tMjvJm+0MLdx1qef95QKzlIT4CnlkbQKEQuWNVGmeiiJL+4HH0Ak3Bc88co/QyLssGF8OJlMbr9Ht4cjsY89/9REfZUHWa8wCdyoPdkqv49qNBVVC/VLoWBwAN/wO4iIHB90j/BG5FLb/ATL1kuRnl8u2un6RBmcbFE8jxRiozbcy6zmqYIupDsowtq/oe4c2ZdAgcPAkb8EAOt0qJn8PGSPPOxyydAguepJtltqv2T9Xwtnac2j7rTW1oFbTtqVUrO/Wp+7wbV0Z28S3dO0KJqz2KkXnoAn50kSSDPaIVbYEih8ko005GAuUW3wN6J9MJgacRs3bmwHlFDxqd0DziG6Sk7TlMLa8lIzAQHL1cc4O3WGoWokw=
  - secure: cZ5VlxiNY+JAXNabTIe0jHbWDKp0dFyOJ+keEQ2HxTdbIWwiTa6xdeAoUwizb+EYIF+wIam6aE1N77rzrTrUbMS2wJbWEK7snJtuRV/Lb5a6ztfyFkJe10JDgk+1HpwbZeOVojueZxq4tFdYwPrE+5wOHZ8fyrTjwZ6SMobEDKLWORJMstbbGmgcsjkx9O7CBjwaex8Z4cZqA2tL4MLSVWCyYMPJwmHFRcnV0z8GIatgGrmBK0EwK+zwPCWLd0xpA2Ia0fGnFba4agwV65ynlyhAqOPC8FxLYLkoHWzzBiWv1f9YHQMJT+N7JiJnSA0oFXbKaEiFOG+Z2QN9JkhLHcMz+6Pl2wSMcs3Y6/kQpJi+/opAphe4qUoinznUGZcNlSDN19c+QHUprutablJvJ0ABprOCsjKiT4YQ+lLmMIc+EwXLYAVi3yaPqYPywYNb+OLjWJp7mf/pBpbR16hF4nkzQoogf7FBgqGtYTXmUNeQ8DO/APLwg/f6isEbmVkP03k/VqQIhMxP9Xtnt2FVkbmpa7olMWypbkjhI8PrY8fyWlBClqEkK++nGvHVBabelf7VjUB+9sumRoyVpw3h3pa8HYp5jgnQrQrhuqBNHZue0ZldiAa/ANz1S1Ji7KdhIFLBMahjBKr6Sch+auCfFCBP6hooQdRXF1Yt/LrsPGY=
